name: Deploy AWS Lambda
on:
  push:
    branches:
      - main

jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: zip -r -j python-lambda.zip ./python-lambda
      - run: unzip -l python-lambda.zip