name: Deploy AWS Lambda
on:
  push:
    branches:
      - main

jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            python-lambda
      - run: zip -r python-lambda.zip .
      - run: unzip -l python-lambda.zip